### ISSUE TITLE
unkonw issue

### ISSUE THREAD

**Issue by mrcalzon02** [Ogliss/AdMechArmoury#10]
https://steamuserimages-a.akamaihd.net/ugc/1689397486609006598/03AAFA21D776D882933382AD57E1AC3922DE33FB/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Ogliss** [comment]
no logs, no mention of these mods, closing this issue
