### ISSUE TITLE
Reseacrh is bonked and i con make all stuff i should be able to

### ISSUE THREAD

**Issue by Sanek12382** [Ogliss/AdMechArmoury#12]
![image](https://user-images.githubusercontent.com/58268711/127549743-fc242b17-3834-4587-8c8b-2251891e2672.png)
![image](https://user-images.githubusercontent.com/58268711/127549866-d53189be-49c0-4325-a84e-bbdfa993a71c.png)
![image](https://user-images.githubusercontent.com/58268711/127549893-339020ab-59f5-4ebb-ab5a-2471863f03b9.png)
what is more confusing is dubs mint menus can see what i should be able to make yet i can order to make it there either 
![image](https://user-images.githubusercontent.com/58268711/127549993-59ec51e2-de02-4dfb-8320-8ae628feca68.png)

**Comment by Sanek12382** [comment]
*cant make thought dubs mint menus

**Comment by Sanek12382** [comment]
[Mechanicus Colony30.zip](https://github.com/Ogliss/AdMechArmoury/files/6903043/Mechanicus.Colony30.zip)
also here is my save file and im quite certain that my exessive amount of mods caused it

**Comment by Ogliss** [comment]
do you actually have any members of the mechanicus race in your colony?, it looks like the alien race restrictions are stopping you from crafting things(or your missing prewquistes that dubs mint menu isnt showing)

**Comment by Ogliss** [comment]
im afraid as im not subbed to the vast majority of those mods im not able to test it without manually searching and subbing to each.

have you checked in the vanilla research menu?

**Comment by Sanek12382** [comment]
I started as mechanicus in custom scenarios thing and what are pawn type names in dev spawn menu I’ll try to get one

**Comment by Sanek12382** [comment]
hey so i just reseached a bucnch of other tech from the mod and it sorta figured it self out
