### ISSUE TITLE
Admech Armoury Bolters not considered ranged weapons

### ISSUE THREAD

**Issue by mrmikeman38** [Ogliss/AdMechArmoury#22]
As the title says. 

I have multiple pawns assigned to hunting and equipped with bolters from this mod. All was well until i updated some mods and now i get the error "Hunter Lacks Ranged Weapon" on all my pawns with bolters

**Comment by Ogliss** [comment]
a couple folks have reported this recently, same story, fine till some mods updated, leads me to believe that its a conflict with something else, as i cant reproduce this locally

**Comment by mrmikeman38** [comment]
I've yet to be able to isolate which mod is causing it which is really annoying.....

**Comment by Ogliss** [comment]
if you gen a hugslib log, theres a good chance the culprit will be patching hunting weapons code, should be visable in the list of patches

**Comment by mrmikeman38** [comment]
would you like a copy of said log?

**Comment by Ogliss** [comment]
Aye, sorry, that was the intent :)

**Comment by mrmikeman38** [comment]
https://gist.github.com/4fc72e4cf70ba4110cb105c4254068e2

Doesn't look like there's any reference to hunting other than the base defs

I might just be looking wrong XD

**Comment by Ogliss** [comment]
only mod patching hunting methods there is MVCF, part of Vanillia Expanded

**Comment by mrmikeman38** [comment]
ah that's what MVCF is.

I think it's the mechanoid faction expanded

**Comment by mrmikeman38** [comment]
should I report it to the VE Team?

**Comment by Ogliss** [comment]
test to see if it occurs without it first, im afraid i dont use any VE mods myself, so not something i tend to rest with. If it no longer occurs without the VE core mod loaded, then you can try reporting it to them

**Comment by mrmikeman38** [comment]
Righto cheers for all your help
